import './globals.css';
import Link from 'next/link';
import Image from 'next/image';
import { Indie_Flower } from '@next/font/google';

const indieFlower = Indie_Flower({ weight: '400' });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Tabemos | Food blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <header
          className={`${indieFlower.className} bg-pink-300 cursor-pointer w-full flex flex-row justify-center items-center`}
        >
          <Link href="/">
            <div className="title">
              <h1 className="text-3xl">Minna tabemos</h1>
              <span>with Noa</span>
            </div>
          </Link>
          <a
            href="https://www.instagram.com/minnaisho/"
            target="_blank"
            rel="noreferrer"
          >
            <Image
              alt="logo"
              height={80}
              width={80}
              className="ml-3 rounded-full"
              src="/noa.png"
            />
          </a>
        </header>
        <div className="text-center mt-7 p-8 m-auto">{children}</div>
        <footer className="bg-gray-800 flex p-2 text-white justify-center">
          <a rel="me" href="https://fosstodon.org/@ricardodevis">
            Follow me on Mastodon
          </a>
        </footer>
      </body>
    </html>
  );
}
